# Site settings
baseurl = "https://www.mendydrinks.com/"
languageCode = "en-us"
title = "Mendy Drinks"
theme = "ghostwriter"
copyright = "Mendy Berkowitz"
googleAnalytics = "UA-79306-5"

[Author]
	name = "Mendy Berkowitz"
	profile = "https://instagram.com/mendy_drinks"

[Taxonomies]
	tag = "tags"

[Params]
  intro = true
  headline = "Mendy Drinks"
  #description = "Mendy Drinks"
  sharegoogleplus = false

[Permalinks]
	post = "/:year/:month/:day/:filename/"

[outputFormats.jsonfeed]
	mediaType = "application/json"
	baseName = "feed"
	isPlainText = true

[outputs]
	home = ["html", "jsonfeed", "rss"]	
